<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Matchbook.Purchasing.Application\Matchbook.Purchasing.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Matchbook.BuildingBlocks\Matchbook.BuildingBlocks.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Matchbook.Purchasing.IntegrationTests" />
  </ItemGroup>

</Project>
