<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Matchbook.Requisitions.Infrastructure\Matchbook.Requisitions.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Matchbook.Requisitions.IntegrationTests" />
  </ItemGroup>

</Project>
