<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Matchbook.Purchasing.Infrastructure\Matchbook.Purchasing.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Matchbook.Purchasing.IntegrationTests" />
  </ItemGroup>

</Project>
