// <auto-generated />
using System;
using System.Collections.Generic;
using Matchbook.Payables.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Matchbook.Payables.Infrastructure.Migrations
{
    [DbContext(typeof(PayablesDbContext))]
    [Migration("20260924053006_AccountNumbersStayEncrypted")]
    partial class AccountNumbersStayEncrypted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<Guid>("CapturedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("captured_by");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTimeOffset?>("DuplicateClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duplicate_cleared_at");

                    b.Property<Guid?>("DuplicateClearedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_cleared_by");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<DateTimeOffset?>("MatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("matched_at");

                    b.Property<string>("NormalisedNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalised_number");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reason");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason_detail");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid?>("SuspectedDuplicateOf")
                        .HasColumnType("uuid")
                        .HasColumnName("suspected_duplicate_of");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<string>("VarianceAcceptanceReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("variance_acceptance_reason");

                    b.Property<DateTimeOffset?>("VarianceAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("variance_accepted_at");

                    b.Property<Guid?>("VarianceAcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("variance_accepted_by");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("PurchaseOrderId", "Status")
                        .HasDatabaseName("ix_invoices_purchase_order_id_status");

                    b.HasIndex("Status", "DueDate")
                        .HasDatabaseName("ix_invoices_status_due_date");

                    b.HasIndex("Status", "Id")
                        .HasDatabaseName("ix_invoices_status_id");

                    b.HasIndex("SupplierId", "NormalisedNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_invoices_supplier_number")
                        .HasFilter("status <> 'Rejected'");

                    b.HasIndex("SupplierId", "Total")
                        .HasDatabaseName("ix_invoices_supplier_id_total");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_duplicate_second_person", "duplicate_cleared_by IS NULL OR duplicate_cleared_by <> captured_by");

                            t.HasCheckConstraint("ck_invoices_total_positive", "total > 0");

                            t.HasCheckConstraint("ck_invoices_variance_second_person", "variance_accepted_by IS NULL OR variance_accepted_by <> captured_by");
                        });
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Orders.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Number")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Orders.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_receipts_purchase_order_id");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.PaymentRuns.PaymentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("DraftedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("drafted_at");

                    b.Property<Guid>("DraftedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by");

                    b.Property<DateOnly>("ExecutionDate")
                        .HasColumnType("date")
                        .HasColumnName("execution_date");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<int>("PaidCount")
                        .HasColumnType("integer")
                        .HasColumnName("paid_count");

                    b.Property<decimal>("PaidTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_total");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_payment_runs");

                    b.ToTable("payment_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_runs_released_by_second_treasurer", "released_by IS NULL OR released_by <> drafted_by");
                        });
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.PaymentRuns.PaymentRunItem", b =>
                {
                    b.Property<Guid>("PaymentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_run_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supplier_invoice_number");

                    b.HasKey("PaymentRunId", "InvoiceId")
                        .HasName("pk_payment_run_items");

                    b.HasIndex("InvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_run_items_active_invoice")
                        .HasFilter("status IN ('Scheduled', 'Paid')");

                    b.HasIndex("PaymentRunId", "Status", "SupplierId")
                        .HasDatabaseName("ix_payment_run_items_payment_run_id_status_supplier_id");

                    b.ToTable("payment_run_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_run_items_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Suppliers.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<int>("PaymentTermsDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms_days");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Account", "Matchbook.Payables.Domain.Suppliers.Supplier.Account#SupplierAccount", b1 =>
                        {
                            b1.Property<string>("AccountHolder")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("account_holder");

                            b1.Property<int>("AccountVersion")
                                .HasColumnType("integer")
                                .HasColumnName("account_version");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("account_bic");

                            b1.Property<string>("IbanLastFour")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("account_iban_last_four");

                            b1.Property<string>("ProtectedIban")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_protected_iban");
                        });

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", null, t =>
                        {
                            t.HasCheckConstraint("ck_suppliers_account_iban_protected", "account_protected_iban IS NULL OR account_protected_iban LIKE 'v1.%'");
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Invoices.Invoice", b =>
                {
                    b.OwnsMany("Matchbook.Payables.Domain.Invoices.InvoiceLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid")
                                .HasColumnName("invoice_id");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.HasKey("InvoiceId", "LineNumber")
                                .HasName("pk_invoice_lines");

                            b1.ToTable("invoice_lines", null, t =>
                                {
                                    t.HasCheckConstraint("ck_invoice_lines_quantity_positive", "quantity > 0");

                                    t.HasCheckConstraint("ck_invoice_lines_unit_price_not_negative", "unit_price >= 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId")
                                .HasConstraintName("fk_invoice_lines_invoices_invoice_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Orders.PurchaseOrder", b =>
                {
                    b.OwnsMany("Matchbook.Payables.Domain.Orders.OrderedLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("purchase_order_id");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.HasKey("PurchaseOrderId", "LineNumber")
                                .HasName("pk_purchase_order_lines");

                            b1.ToTable("purchase_order_lines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId")
                                .HasConstraintName("fk_purchase_order_lines_purchase_orders_purchase_order_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.Orders.Receipt", b =>
                {
                    b.OwnsMany("Matchbook.Payables.Domain.Orders.ReceivedLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("ReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("receipt_id");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("quantity");

                            b1.HasKey("ReceiptId", "LineNumber")
                                .HasName("pk_receipt_lines");

                            b1.ToTable("receipt_lines", null, t =>
                                {
                                    t.HasCheckConstraint("ck_receipt_lines_quantity_positive", "quantity > 0");
                                });

                            b1.WithOwner()
                                .HasForeignKey("ReceiptId")
                                .HasConstraintName("fk_receipt_lines_receipts_receipt_id");
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.PaymentRuns.PaymentRun", b =>
                {
                    b.OwnsMany("Matchbook.Payables.Domain.PaymentRuns.PaymentRunCreditor", "Creditors", b1 =>
                        {
                            b1.Property<Guid>("PaymentRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("payment_run_id");

                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid")
                                .HasColumnName("supplier_id");

                            b1.Property<string>("AccountHolder")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("account_holder");

                            b1.Property<int>("AccountVersion")
                                .HasColumnType("integer")
                                .HasColumnName("account_version");

                            b1.Property<string>("Bic")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("bic");

                            b1.Property<string>("DropReason")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("drop_reason");

                            b1.Property<string>("IbanLastFour")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("iban_last_four");

                            b1.Property<int>("ItemCount")
                                .HasColumnType("integer")
                                .HasColumnName("item_count");

                            b1.Property<string>("ProtectedIban")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("protected_iban");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("status");

                            b1.Property<decimal>("Total")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total");

                            b1.HasKey("PaymentRunId", "SupplierId")
                                .HasName("pk_payment_run_creditors");

                            b1.ToTable("payment_run_creditors", null, t =>
                                {
                                    t.HasCheckConstraint("ck_payment_run_creditors_iban_protected", "protected_iban LIKE 'v1.%'");
                                });

                            b1.WithOwner()
                                .HasForeignKey("PaymentRunId")
                                .HasConstraintName("fk_payment_run_creditors_payment_runs_payment_run_id");
                        });

                    b.Navigation("Creditors");
                });

            modelBuilder.Entity("Matchbook.Payables.Domain.PaymentRuns.PaymentRunItem", b =>
                {
                    b.HasOne("Matchbook.Payables.Domain.Invoices.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_run_items_invoices_invoice_id");

                    b.HasOne("Matchbook.Payables.Domain.PaymentRuns.PaymentRun", null)
                        .WithMany()
                        .HasForeignKey("PaymentRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_run_items_payment_runs_payment_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
